server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.194.103:8848


logging:
  level:
    com.chiiiplow.gulimall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
